# -*- coding: utf-8 -*-
"""Devopsv2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HTaiyihOSdfgIydWabn5QBuzl45O_bIB
"""

import pandas as pd
import numpy as np


from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix , classification_report

from google.colab import drive
drive.mount('/content/gdrive')

import os
PATH='/content/gdrive/MyDrive/Machine Learning Modelling'
os.chdir(PATH)

!ls

data = pd.read_csv('BankNote.csv', na_values=['#','?'])

data

data.head(5)

data.tail(5)

data.shape

data.isna().sum()

data.nunique()

data.dtypes

data.corr()

data.describe()

x_train, x_test , y_train , y_test = train_test_split(data.loc[:,data.columns !='class'], data.loc[:,'class'], test_size=0.3, random_state=123)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

x_train.head()

x_train.isna().sum()

x_test.isna().sum()

std = StandardScaler()

x_train= pd.DataFrame(std.fit_transform(x_train), columns=x_train.columns)
x_test= pd.DataFrame(std.transform(x_test), columns=x_test.columns)

x_train.head()

x_train.shape

x_test.shape



model = LogisticRegression()

model.fit(x_train, y_train)

train_pred_lg=model.predict(x_train)

validation_pred_lg=model.predict(x_test)

confusion_matrix(y_train, train_pred_lg)

print(classification_report(y_train, train_pred_lg))

confusion_matrix(y_test, validation_pred_lg)

print(classification_report(y_test, validation_pred_lg))

